server:
  port: 9632
  servlet:
    context-path: /api


spring:
  datasource:
    guard:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.9.42:3306/guard_home_demo?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: guard
      password: txsqldb@123456

