server:
  servlet:
    context-path: /job/api
    session:
      timeout: PT30M
  max-http-post-size: 1048576000
  max-http-header-size: 1048576000


spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: zans-job
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
