server:
  port: 8765
app:
  name: alert-api
spring:
  charset: utf-8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

logging:
  config: logback.xml

alert:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: txsqldb@123456
    url: jdbc:mysql://192.168.9.51:3306/guard_scan_whzk?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: guard
job:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: txsqldb@123456
    url: jdbc:mysql://192.168.9.51:3306/guard_job?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: guard

request:
  jobApi: http://192.168.9.42:15367/job/api/job/


