server:
  port: 19681
  servlet:
    context-path: /api
logging:
  config: logback.xml

spring:
  datasource:
    guard:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.9.42:3306/guard_scan?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: guard
      password: txsqldb@123456
    radius:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.9.42:3306/radius?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: guard
      password: txsqldb@123456
  # REDIS数据库配置
  redis:
    lettuce:
      pool:
        max-idle: 100
        max-wait: 2000
        min-idle: 50
    auth:
      # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
      host: 192.168.9.42
      # [必须修改] 端口号
      port: 6379
      # [可选] 数据库 DB
      database: 2
      # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
      password: redis123
    acct:
      # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
      host: 192.168.9.42
      # [必须修改] 端口号
      port: 6379
      # [可选] 数据库 DB
      database: 3
      # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
      password: redis123
    alive:
      # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
      host: 192.168.9.42
      # [必须修改] 端口号
      port: 6379
      # [可选] 数据库 DB
      database: 10
      # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
      password: redis123
