server:
  port: 6666
  ssl:
    enabled: false
  undertow:
    io-threads: 4
    worker-threads: 32
    max-http-post-size: 0


spring:
  datasource:
    guard:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.30.100:3306/nms_test?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: guard
      password: txsqldb@123456


security:
  exclude-path:
    swagger: /swagger-ui.html, /swagger/**, /swagger-resources/**, /webjars/**, /v2/api-docs, /statics/**, /doc.html
    base: /login, /logout, /verify_login, /app/login, /app/logout, /app/verify_login,/app/loginByWxCode,/app/loginByWxPhone,/error, /favicon.ico, /constant/**, /ip/alloc/download/**, /ip/import/**, /hello, /network/**, /segment/**
    api: /home/**, /rbac/**, /user/current, /person/**, /durid/**,/user/me,/user/change_password, /base/**, /app/**,/app/base/**
  user-verify: jwt
  jwt:
    expire-time: 60000000
    app-expire-time: 60000000000


api:
  upload:
    folder: /home/release/file/upload/
    max-size: 5
  export:
    folder: /home/release/file/export/
  imgUrl:
    folder: /home/release/img/

request:
  wechat:
    url: https://127.0.0.1:10000/wxpush_api

logging:
  level:
    com.zans.mms.dao : info

patrol:
  task: 0
