server:
  port: 6666
  ssl:
    enabled: false
  undertow:
    io-threads: 4
    worker-threads: 32
    max-http-post-size: 0


spring:
  datasource:
    guard:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://27.10.30.67:3306/mms?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
      username: guard_2
      password: Txsqldb@123456
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    #host: 192.168.9.40
    host: 27.10.30.67
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 6
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    #password: redis123
    password: redis123
    # [可选] 超时时间
    timeout: 10000

security:
  exclude-path:
    swagger: /swagger-ui.html, /swagger/**, /swagger-resources/**, /webjars/**, /v2/api-docs, /statics/**, /doc.html
    base: /login, /logout, /verify_login, /app/login, /app/logout, /app/verify_login,/app/loginByWxCode,/app/loginByWxPhone,/error, /favicon.ico, /constant/**, /ip/alloc/download/**, /ip/import/**, /hello, /network/**, /segment/**
    api: /home/**, /rbac/**, /user/current, /person/**, /durid/**,/user/me,/user/change_password, /base/**, /app/**,/app/base/**
  user-verify: jwt
  jwt:
    expire-time: 60000000
    app-expire-time: 6000000000


api:
  upload:
    folder: /home/release/file/upload/
    max-size: 5
  export:
    folder: /home/release/file/export/
  imgUrl:
    folder: /home/release/img/
  diagnosis:
    folder: /home/release/diagnosis/

request:
  wechat:
    url: https://27.10.28.66:10000/wxpush_api
  diagnosis:
    url: http://27.10.30.98:8888/diagnosis/
file:
  img:
    retentionDays: 60

#logging:
#  level:
#    com.zans.mms.dao : debug

mock-api:
  mock-dir: ./mock

patrol:
  task: 0
