all:
  children:
    policy_group:
      hosts:
        policy01.lgwy.com:
          ansible_ssh_host: 192.168.9.42
          ansible_ssh_user: root
          ansible_ssh_pass: Admin#12$34!
          ansible_connection: ssh
    scan_group:
      hosts:
        scan01.lgwy.com:
          ansible_ssh_host: 192.168.9.42
          ansible_ssh_user: root
          ansible_ssh_pass: Admin#12$34!
          ansible_connection: ssh
        scan02.lgwy.com:
          ansible_ssh_host: 192.168.9.100
          ansible_ssh_user: root
          ansible_ssh_pass: Admin#12$34!
          ansible_connection: ssh
        scan03.lgwy.com:
          ansible_ssh_host: 192.168.9.101
          ansible_ssh_user: root
          ansible_ssh_pass: Admin#12$34!
          ansible_connection: ssh
    
      
