// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person2.proto

package com.pancm.test.protobufTest.protobuf3;

/**
 * The type Person msg 2.
 */
public final class PersonMsg2 {
  private PersonMsg2() {}

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

    /**
     * The interface Person or builder.
     */
    public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * ID（必需）
         * </pre>
         *
         * <code>optional int32 id = 1;</code>
         *
         * @return the id
         */
        int getId();

        /**
         * <pre>
         * 姓名（必需）
         * </pre>
         *
         * <code>optional string name = 2;</code>
         *
         * @return the name
         */
        java.lang.String getName();

        /**
         * <pre>
         * 姓名（必需）
         * </pre>
         *
         * <code>optional string name = 2;</code>
         *
         * @return the name bytes
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <pre>
         * email（可选）
         * </pre>
         *
         * <code>optional string email = 3;</code>
         *
         * @return the email
         */
        java.lang.String getEmail();

        /**
         * <pre>
         * email（可选）
         * </pre>
         *
         * <code>optional string email = 3;</code>
         *
         * @return the email bytes
         */
        com.google.protobuf.ByteString
        getEmailBytes();

        /**
         * <pre>
         * 朋友（集合）
         * </pre>
         *
         * <code>optional string friends = 4;</code>
         *
         * @return the friends
         */
        java.lang.String getFriends();

        /**
         * <pre>
         * 朋友（集合）
         * </pre>
         *
         * <code>optional string friends = 4;</code>
         *
         * @return the friends bytes
         */
        com.google.protobuf.ByteString
        getFriendsBytes();
  }

    /**
     * Protobuf type {@code Person}
     */
    public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      id_ = 0;
      name_ = "";
      email_ = "";
      friends_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              friends_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

        /**
         * Gets descriptor.
         *
         * @return the descriptor
         */
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pancm.test.protobufTest.protobuf3.PersonMsg2.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pancm.test.protobufTest.protobuf3.PersonMsg2.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.class, com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.Builder.class);
    }

        /**
         * The constant ID_FIELD_NUMBER.
         */
        public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * ID（必需）  
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

        /**
         * The constant NAME_FIELD_NUMBER.
         */
        public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名（必需）  
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名（必需）  
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

        /**
         * The constant EMAIL_FIELD_NUMBER.
         */
        public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <pre>
     * email（可选）  
     * </pre>
     *
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * email（可选）  
     * </pre>
     *
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

        /**
         * The constant FRIENDS_FIELD_NUMBER.
         */
        public static final int FRIENDS_FIELD_NUMBER = 4;
    private volatile java.lang.Object friends_;
    /**
     * <pre>
     * 朋友（集合）  
     * </pre>
     *
     * <code>optional string friends = 4;</code>
     */
    public java.lang.String getFriends() {
      java.lang.Object ref = friends_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friends_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 朋友（集合）  
     * </pre>
     *
     * <code>optional string friends = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFriendsBytes() {
      java.lang.Object ref = friends_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friends_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getFriendsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, friends_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getFriendsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, friends_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person)) {
        return super.equals(obj);
      }
      com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person other = (com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getFriends()
          .equals(other.getFriends());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
      hash = (53 * hash) + getFriends().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param data the data
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws InvalidProtocolBufferException the invalid protocol buffer exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param data              the data
         * @param extensionRegistry the extension registry
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws InvalidProtocolBufferException the invalid protocol buffer exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param data the data
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws InvalidProtocolBufferException the invalid protocol buffer exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param data              the data
         * @param extensionRegistry the extension registry
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws InvalidProtocolBufferException the invalid protocol buffer exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input the input
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input             the input
         * @param extensionRegistry the extension registry
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

        /**
         * Parse delimited from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input the input
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

        /**
         * Parse delimited from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input             the input
         * @param extensionRegistry the extension registry
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input the input
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

        /**
         * Parse from com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person.
         *
         * @param input             the input
         * @param extensionRegistry the extension registry
         * @return the com . pancm . test . protobuf test . protobuf 3 . person msg 2 . person
         * @throws IOException the io exception
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }

        /**
         * New builder builder.
         *
         * @return the builder
         */
        public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

        /**
         * New builder builder.
         *
         * @param prototype the prototype
         * @return the builder
         */
        public static Builder newBuilder(com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

        /**
         * Protobuf type {@code Person}
         */
        public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.pancm.test.protobufTest.protobuf3.PersonMsg2.PersonOrBuilder {
            /**
             * Gets descriptor.
             *
             * @return the descriptor
             */
            public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pancm.test.protobufTest.protobuf3.PersonMsg2.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pancm.test.protobufTest.protobuf3.PersonMsg2.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.class, com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.Builder.class);
      }

      // Construct using com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        friends_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pancm.test.protobufTest.protobuf3.PersonMsg2.internal_static_Person_descriptor;
      }

      public com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person getDefaultInstanceForType() {
        return com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.getDefaultInstance();
      }

      public com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person build() {
        com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person buildPartial() {
        com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person result = new com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person(this);
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        result.friends_ = friends_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person) {
          return mergeFrom((com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

            /**
             * Merge from builder.
             *
             * @param other the other
             * @return the builder
             */
            public Builder mergeFrom(com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person other) {
        if (other == com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getFriends().isEmpty()) {
          friends_ = other.friends_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * ID（必需）  
       * </pre>
       *
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

            /**
             * <pre>
             * ID（必需）
             * </pre>
             *
             * <code>optional int32 id = 1;</code>
             *
             * @param value the value
             * @return the id
             */
            public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }

            /**
             * <pre>
             * ID（必需）
             * </pre>
             *
             * <code>optional int32 id = 1;</code>
             *
             * @return the builder
             */
            public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名（必需）  
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名（必需）  
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

            /**
             * <pre>
             * 姓名（必需）
             * </pre>
             *
             * <code>optional string name = 2;</code>
             *
             * @param value the value
             * @return the name
             */
            public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }

            /**
             * <pre>
             * 姓名（必需）
             * </pre>
             *
             * <code>optional string name = 2;</code>
             *
             * @return the builder
             */
            public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

            /**
             * <pre>
             * 姓名（必需）
             * </pre>
             *
             * <code>optional string name = 2;</code>
             *
             * @param value the value
             * @return the name bytes
             */
            public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <pre>
       * email（可选）  
       * </pre>
       *
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * email（可选）  
       * </pre>
       *
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

            /**
             * <pre>
             * email（可选）
             * </pre>
             *
             * <code>optional string email = 3;</code>
             *
             * @param value the value
             * @return the email
             */
            public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }

            /**
             * <pre>
             * email（可选）
             * </pre>
             *
             * <code>optional string email = 3;</code>
             *
             * @return the builder
             */
            public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }

            /**
             * <pre>
             * email（可选）
             * </pre>
             *
             * <code>optional string email = 3;</code>
             *
             * @param value the value
             * @return the email bytes
             */
            public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friends_ = "";
      /**
       * <pre>
       * 朋友（集合）  
       * </pre>
       *
       * <code>optional string friends = 4;</code>
       */
      public java.lang.String getFriends() {
        java.lang.Object ref = friends_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friends_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 朋友（集合）  
       * </pre>
       *
       * <code>optional string friends = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFriendsBytes() {
        java.lang.Object ref = friends_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friends_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

            /**
             * <pre>
             * 朋友（集合）
             * </pre>
             *
             * <code>optional string friends = 4;</code>
             *
             * @param value the value
             * @return the friends
             */
            public Builder setFriends(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friends_ = value;
        onChanged();
        return this;
      }

            /**
             * <pre>
             * 朋友（集合）
             * </pre>
             *
             * <code>optional string friends = 4;</code>
             *
             * @return the builder
             */
            public Builder clearFriends() {
        
        friends_ = getDefaultInstance().getFriends();
        onChanged();
        return this;
      }

            /**
             * <pre>
             * 朋友（集合）
             * </pre>
             *
             * <code>optional string friends = 4;</code>
             *
             * @param value the value
             * @return the friends bytes
             */
            public Builder setFriendsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friends_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person();
    }

        /**
         * Gets default instance.
         *
         * @return the default instance
         */
        public static com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

        /**
         * Parser com . google . protobuf . parser.
         *
         * @return the com . google . protobuf . parser
         */
        public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.pancm.test.protobufTest.protobuf3.PersonMsg2.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPerson2.proto\"B\n\006Person\022\n\n\002id\030\001 \001(\005\022\014\n" +
      "\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\017\n\007friends\030\004 " +
      "\001(\tB3\n%com.pancm.test.protobufTest.proto" +
      "buf3B\nPersonMsg2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Friends", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
